### ISSUE TITLE
Internal Server Error after Gmail Login

### ISSUE THREAD

**Issue by himadriganguly** [flipkart-incubator/mafia#5]
After login through Gmail Account getting "Internal Server Error" on the Frontend and in the console it is giving 
`OAuthException: Invalid response from google
2018-10-06T10:59:55Z {'REMOTE_PORT': '48322', 'HTTP_HOST': 'localhost:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 24)} failed with OAuthException`

**Comment by mohangcsm** [comment]
Please make sure the mafia domain (including the port) is whitelisted in Google OAuth2 credentials (https://console.developers.google.com/apis/credentials) and also please make sure that Google accounts domain (https://accounts.google.com) is accessible from the Mafia Box.

For further debugging, please share us the complete console log of the login flow.

**Comment by Jiadosi** [comment]
what is the SECRET_KEY means?

**Comment by Jiadosi** [comment]
Server Started on: https://0.0.0.0:5444/
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 201, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 695, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 198, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory
2018-12-07T06:16:40Z <Greenlet "Greenlet-0" at 0x7fe54a637470: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe54a1b4c10 fileno=[Errno 9] Bad fi)> failed with IOError
